services:
    db:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            - external_network
        env_file:
            - ./docker.env
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

networks:
    external_network:
